//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPrueba.ServiceReferenceWSProveedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaIngresarServicio", Namespace="http://wsproveedor1.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaIngresarServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsproveedor1.org/", ConfigurationName="ServiceReferenceWSProveedor.WSProveedorSoap")]
    public interface WSProveedorSoap {
        
        // CODEGEN: Generating message contract since element name numeroTelefono from namespace http://wsproveedor1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/IngresarNuevoServicio", ReplyAction="*")]
        TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse IngresarNuevoServicio(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/IngresarNuevoServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicio", Namespace="http://wsproveedor1.org/", Order=0)]
        public TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequestBody Body;
        
        public IngresarNuevoServicioRequest() {
        }
        
        public IngresarNuevoServicioRequest(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        public IngresarNuevoServicioRequestBody() {
        }
        
        public IngresarNuevoServicioRequestBody(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            this.numeroTelefono = numeroTelefono;
            this.idTelefono = idTelefono;
            this.idTarjeta = idTarjeta;
            this.tipo = tipo;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicioResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponseBody Body;
        
        public IngresarNuevoServicioResponse() {
        }
        
        public IngresarNuevoServicioResponse(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestPrueba.ServiceReferenceWSProveedor.RespuestaIngresarServicio IngresarNuevoServicioResult;
        
        public IngresarNuevoServicioResponseBody() {
        }
        
        public IngresarNuevoServicioResponseBody(TestPrueba.ServiceReferenceWSProveedor.RespuestaIngresarServicio IngresarNuevoServicioResult) {
            this.IngresarNuevoServicioResult = IngresarNuevoServicioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProveedorSoapChannel : TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProveedorSoapClient : System.ServiceModel.ClientBase<TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap>, TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap {
        
        public WSProveedorSoapClient() {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap.IngresarNuevoServicio(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest request) {
            return base.Channel.IngresarNuevoServicio(request);
        }
        
        public TestPrueba.ServiceReferenceWSProveedor.RespuestaIngresarServicio IngresarNuevoServicio(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest inValue = new TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest();
            inValue.Body = new TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.estado = estado;
            TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse retVal = ((TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap)(this)).IngresarNuevoServicio(inValue);
            return retVal.Body.IngresarNuevoServicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse> TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap.IngresarNuevoServicioAsync(TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest request) {
            return base.Channel.IngresarNuevoServicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest inValue = new TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequest();
            inValue.Body = new TestPrueba.ServiceReferenceWSProveedor.IngresarNuevoServicioRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.estado = estado;
            return ((TestPrueba.ServiceReferenceWSProveedor.WSProveedorSoap)(this)).IngresarNuevoServicioAsync(inValue);
        }
    }
}
