//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAUTENTICACION
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResponse", Namespace="http://schemas.datacontract.org/2004/07/WSAutenticacion")]
    public partial class AuthResponse : object
    {
        
        private string Apellido1Field;
        
        private string MensajeField;
        
        private string NombreField;
        
        private bool ResultadoField;
        
        private int TipoUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1
        {
            get
            {
                return this.Apellido1Field;
            }
            set
            {
                this.Apellido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Usuario : object
    {
        
        private string apellido1Field;
        
        private string apellido2Field;
        
        private string contrasennaField;
        
        private string correoField;
        
        private string estadoField;
        
        private string identificacionField;
        
        private string nombreField;
        
        private int tipoField;
        
        private string usuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido1
        {
            get
            {
                return this.apellido1Field;
            }
            set
            {
                this.apellido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2
        {
            get
            {
                return this.apellido2Field;
            }
            set
            {
                this.apellido2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenna
        {
            get
            {
                return this.contrasennaField;
            }
            set
            {
                this.contrasennaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAUTENTICACION.IAuthService")]
    public interface IAuthService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/Login", ReplyAction="http://tempuri.org/IAuthService/LoginResponse")]
        System.Threading.Tasks.Task<WSAUTENTICACION.AuthResponse> LoginAsync(string usuarioCifrado, string contrasennaCifrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/RegistrarUsuario", ReplyAction="http://tempuri.org/IAuthService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<WSAUTENTICACION.AuthResponse> RegistrarUsuarioAsync(WSAUTENTICACION.Usuario nuevoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/ObtenerAdministradores", ReplyAction="http://tempuri.org/IAuthService/ObtenerAdministradoresResponse")]
        System.Threading.Tasks.Task<WSAUTENTICACION.Usuario[]> ObtenerAdministradoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAuthServiceChannel : WSAUTENTICACION.IAuthService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<WSAUTENTICACION.IAuthService>, WSAUTENTICACION.IAuthService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthServiceClient() : 
                base(AuthServiceClient.GetDefaultBinding(), AuthServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WSAUTENTICACION.AuthResponse> LoginAsync(string usuarioCifrado, string contrasennaCifrada)
        {
            return base.Channel.LoginAsync(usuarioCifrado, contrasennaCifrada);
        }
        
        public System.Threading.Tasks.Task<WSAUTENTICACION.AuthResponse> RegistrarUsuarioAsync(WSAUTENTICACION.Usuario nuevoUsuario)
        {
            return base.Channel.RegistrarUsuarioAsync(nuevoUsuario);
        }
        
        public System.Threading.Tasks.Task<WSAUTENTICACION.Usuario[]> ObtenerAdministradoresAsync()
        {
            return base.Channel.ObtenerAdministradoresAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50339/AuthService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthService,
        }
    }
}
