//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedorRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaIngresarServicio", Namespace="http://wsproveedor1.org/")]
    public partial class RespuestaIngresarServicio : object
    {
        
        private bool ResultadoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaDisponible", Namespace="http://wsproveedor1.org/")]
    public partial class LineaDisponible : object
    {
        
        private string NumeroField;
        
        private string IdTarjetaField;
        
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IdTarjeta
        {
            get
            {
                return this.IdTarjetaField;
            }
            set
            {
                this.IdTarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaActivarDesactivar", Namespace="http://wsproveedor1.org/")]
    public partial class RespuestaActivarDesactivar : object
    {
        
        private bool ResultadoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCalculoPostpago", Namespace="http://wsproveedor1.org/")]
    public partial class RespuestaCalculoPostpago : object
    {
        
        private bool ResultadoField;
        
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsproveedor1.org/", ConfigurationName="WSProveedorRef.WSProveedorSoap")]
    public interface WSProveedorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/EliminarLinea", ReplyAction="*")]
        System.Threading.Tasks.Task<WSProveedorRef.EliminarLineaResponse> EliminarLineaAsync(WSProveedorRef.EliminarLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/IngresarNuevoServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<WSProveedorRef.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(WSProveedorRef.IngresarNuevoServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/ObtenerLineasDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<WSProveedorRef.ObtenerLineasDisponiblesResponse> ObtenerLineasDisponiblesAsync(WSProveedorRef.ObtenerLineasDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/ActivarDesactivarLinea", ReplyAction="*")]
        System.Threading.Tasks.Task<WSProveedorRef.ActivarDesactivarLineaResponse> ActivarDesactivarLineaAsync(WSProveedorRef.ActivarDesactivarLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/CalcularCobroPostpago", ReplyAction="*")]
        System.Threading.Tasks.Task<WSProveedorRef.CalcularCobroPostpagoResponse> CalcularCobroPostpagoAsync(WSProveedorRef.CalcularCobroPostpagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarLineaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarLinea", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.EliminarLineaRequestBody Body;
        
        public EliminarLineaRequest()
        {
        }
        
        public EliminarLineaRequest(WSProveedorRef.EliminarLineaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class EliminarLineaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        public EliminarLineaRequestBody()
        {
        }
        
        public EliminarLineaRequestBody(string numeroTelefono)
        {
            this.numeroTelefono = numeroTelefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarLineaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarLineaResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.EliminarLineaResponseBody Body;
        
        public EliminarLineaResponse()
        {
        }
        
        public EliminarLineaResponse(WSProveedorRef.EliminarLineaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class EliminarLineaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSProveedorRef.RespuestaIngresarServicio EliminarLineaResult;
        
        public EliminarLineaResponseBody()
        {
        }
        
        public EliminarLineaResponseBody(WSProveedorRef.RespuestaIngresarServicio EliminarLineaResult)
        {
            this.EliminarLineaResult = EliminarLineaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicio", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.IngresarNuevoServicioRequestBody Body;
        
        public IngresarNuevoServicioRequest()
        {
        }
        
        public IngresarNuevoServicioRequest(WSProveedorRef.IngresarNuevoServicioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        public IngresarNuevoServicioRequestBody()
        {
        }
        
        public IngresarNuevoServicioRequestBody(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado)
        {
            this.numeroTelefono = numeroTelefono;
            this.idTelefono = idTelefono;
            this.idTarjeta = idTarjeta;
            this.tipo = tipo;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicioResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.IngresarNuevoServicioResponseBody Body;
        
        public IngresarNuevoServicioResponse()
        {
        }
        
        public IngresarNuevoServicioResponse(WSProveedorRef.IngresarNuevoServicioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSProveedorRef.RespuestaIngresarServicio IngresarNuevoServicioResult;
        
        public IngresarNuevoServicioResponseBody()
        {
        }
        
        public IngresarNuevoServicioResponseBody(WSProveedorRef.RespuestaIngresarServicio IngresarNuevoServicioResult)
        {
            this.IngresarNuevoServicioResult = IngresarNuevoServicioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerLineasDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerLineasDisponibles", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.ObtenerLineasDisponiblesRequestBody Body;
        
        public ObtenerLineasDisponiblesRequest()
        {
        }
        
        public ObtenerLineasDisponiblesRequest(WSProveedorRef.ObtenerLineasDisponiblesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerLineasDisponiblesRequestBody
    {
        
        public ObtenerLineasDisponiblesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerLineasDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerLineasDisponiblesResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.ObtenerLineasDisponiblesResponseBody Body;
        
        public ObtenerLineasDisponiblesResponse()
        {
        }
        
        public ObtenerLineasDisponiblesResponse(WSProveedorRef.ObtenerLineasDisponiblesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class ObtenerLineasDisponiblesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSProveedorRef.LineaDisponible[] ObtenerLineasDisponiblesResult;
        
        public ObtenerLineasDisponiblesResponseBody()
        {
        }
        
        public ObtenerLineasDisponiblesResponseBody(WSProveedorRef.LineaDisponible[] ObtenerLineasDisponiblesResult)
        {
            this.ObtenerLineasDisponiblesResult = ObtenerLineasDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivarDesactivarLineaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivarDesactivarLinea", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.ActivarDesactivarLineaRequestBody Body;
        
        public ActivarDesactivarLineaRequest()
        {
        }
        
        public ActivarDesactivarLineaRequest(WSProveedorRef.ActivarDesactivarLineaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class ActivarDesactivarLineaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string identificacionDuenio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string estado;
        
        public ActivarDesactivarLineaRequestBody()
        {
        }
        
        public ActivarDesactivarLineaRequestBody(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string identificacionDuenio, string estado)
        {
            this.numeroTelefono = numeroTelefono;
            this.idTelefono = idTelefono;
            this.idTarjeta = idTarjeta;
            this.tipo = tipo;
            this.identificacionDuenio = identificacionDuenio;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivarDesactivarLineaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivarDesactivarLineaResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.ActivarDesactivarLineaResponseBody Body;
        
        public ActivarDesactivarLineaResponse()
        {
        }
        
        public ActivarDesactivarLineaResponse(WSProveedorRef.ActivarDesactivarLineaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class ActivarDesactivarLineaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSProveedorRef.RespuestaActivarDesactivar ActivarDesactivarLineaResult;
        
        public ActivarDesactivarLineaResponseBody()
        {
        }
        
        public ActivarDesactivarLineaResponseBody(WSProveedorRef.RespuestaActivarDesactivar ActivarDesactivarLineaResult)
        {
            this.ActivarDesactivarLineaResult = ActivarDesactivarLineaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularCobroPostpagoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularCobroPostpago", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.CalcularCobroPostpagoRequestBody Body;
        
        public CalcularCobroPostpagoRequest()
        {
        }
        
        public CalcularCobroPostpagoRequest(WSProveedorRef.CalcularCobroPostpagoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class CalcularCobroPostpagoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaCalculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaMaxPago;
        
        public CalcularCobroPostpagoRequestBody()
        {
        }
        
        public CalcularCobroPostpagoRequestBody(string fechaCalculo, string fechaMaxPago)
        {
            this.fechaCalculo = fechaCalculo;
            this.fechaMaxPago = fechaMaxPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularCobroPostpagoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularCobroPostpagoResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public WSProveedorRef.CalcularCobroPostpagoResponseBody Body;
        
        public CalcularCobroPostpagoResponse()
        {
        }
        
        public CalcularCobroPostpagoResponse(WSProveedorRef.CalcularCobroPostpagoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class CalcularCobroPostpagoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSProveedorRef.RespuestaCalculoPostpago CalcularCobroPostpagoResult;
        
        public CalcularCobroPostpagoResponseBody()
        {
        }
        
        public CalcularCobroPostpagoResponseBody(WSProveedorRef.RespuestaCalculoPostpago CalcularCobroPostpagoResult)
        {
            this.CalcularCobroPostpagoResult = CalcularCobroPostpagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WSProveedorSoapChannel : WSProveedorRef.WSProveedorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSProveedorSoapClient : System.ServiceModel.ClientBase<WSProveedorRef.WSProveedorSoap>, WSProveedorRef.WSProveedorSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSProveedorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSProveedorSoapClient.GetBindingForEndpoint(endpointConfiguration), WSProveedorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProveedorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSProveedorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProveedorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSProveedorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSProveedorRef.EliminarLineaResponse> WSProveedorRef.WSProveedorSoap.EliminarLineaAsync(WSProveedorRef.EliminarLineaRequest request)
        {
            return base.Channel.EliminarLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSProveedorRef.EliminarLineaResponse> EliminarLineaAsync(string numeroTelefono)
        {
            WSProveedorRef.EliminarLineaRequest inValue = new WSProveedorRef.EliminarLineaRequest();
            inValue.Body = new WSProveedorRef.EliminarLineaRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            return ((WSProveedorRef.WSProveedorSoap)(this)).EliminarLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSProveedorRef.IngresarNuevoServicioResponse> WSProveedorRef.WSProveedorSoap.IngresarNuevoServicioAsync(WSProveedorRef.IngresarNuevoServicioRequest request)
        {
            return base.Channel.IngresarNuevoServicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSProveedorRef.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado)
        {
            WSProveedorRef.IngresarNuevoServicioRequest inValue = new WSProveedorRef.IngresarNuevoServicioRequest();
            inValue.Body = new WSProveedorRef.IngresarNuevoServicioRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.estado = estado;
            return ((WSProveedorRef.WSProveedorSoap)(this)).IngresarNuevoServicioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSProveedorRef.ObtenerLineasDisponiblesResponse> WSProveedorRef.WSProveedorSoap.ObtenerLineasDisponiblesAsync(WSProveedorRef.ObtenerLineasDisponiblesRequest request)
        {
            return base.Channel.ObtenerLineasDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSProveedorRef.ObtenerLineasDisponiblesResponse> ObtenerLineasDisponiblesAsync()
        {
            WSProveedorRef.ObtenerLineasDisponiblesRequest inValue = new WSProveedorRef.ObtenerLineasDisponiblesRequest();
            inValue.Body = new WSProveedorRef.ObtenerLineasDisponiblesRequestBody();
            return ((WSProveedorRef.WSProveedorSoap)(this)).ObtenerLineasDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSProveedorRef.ActivarDesactivarLineaResponse> WSProveedorRef.WSProveedorSoap.ActivarDesactivarLineaAsync(WSProveedorRef.ActivarDesactivarLineaRequest request)
        {
            return base.Channel.ActivarDesactivarLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSProveedorRef.ActivarDesactivarLineaResponse> ActivarDesactivarLineaAsync(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string identificacionDuenio, string estado)
        {
            WSProveedorRef.ActivarDesactivarLineaRequest inValue = new WSProveedorRef.ActivarDesactivarLineaRequest();
            inValue.Body = new WSProveedorRef.ActivarDesactivarLineaRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.identificacionDuenio = identificacionDuenio;
            inValue.Body.estado = estado;
            return ((WSProveedorRef.WSProveedorSoap)(this)).ActivarDesactivarLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSProveedorRef.CalcularCobroPostpagoResponse> WSProveedorRef.WSProveedorSoap.CalcularCobroPostpagoAsync(WSProveedorRef.CalcularCobroPostpagoRequest request)
        {
            return base.Channel.CalcularCobroPostpagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSProveedorRef.CalcularCobroPostpagoResponse> CalcularCobroPostpagoAsync(string fechaCalculo, string fechaMaxPago)
        {
            WSProveedorRef.CalcularCobroPostpagoRequest inValue = new WSProveedorRef.CalcularCobroPostpagoRequest();
            inValue.Body = new WSProveedorRef.CalcularCobroPostpagoRequestBody();
            inValue.Body.fechaCalculo = fechaCalculo;
            inValue.Body.fechaMaxPago = fechaMaxPago;
            return ((WSProveedorRef.WSProveedorSoap)(this)).CalcularCobroPostpagoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSProveedorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSProveedorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSProveedorSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44354/WSProveedor1/WSProveedor.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSProveedorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44354/WSProveedor1/WSProveedor.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSProveedorSoap,
            
            WSProveedorSoap12,
        }
    }
}
