//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuConsola.ServiceReferenceMenu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaIngresarServicio", Namespace="http://wsproveedor1.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaIngresarServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaActivarDesactivar", Namespace="http://wsproveedor1.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaActivarDesactivar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCalculoPostpago", Namespace="http://wsproveedor1.org/")]
    [System.SerializableAttribute()]
    public partial class RespuestaCalculoPostpago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsproveedor1.org/", ConfigurationName="ServiceReferenceMenu.WSProveedorSoap")]
    public interface WSProveedorSoap {
        
        // CODEGEN: Generating message contract since element name numeroTelefono from namespace http://wsproveedor1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/IngresarNuevoServicio", ReplyAction="*")]
        MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse IngresarNuevoServicio(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/IngresarNuevoServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest request);
        
        // CODEGEN: Generating message contract since element name numeroTelefono from namespace http://wsproveedor1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/ActivarDesactivarLinea", ReplyAction="*")]
        MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse ActivarDesactivarLinea(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/ActivarDesactivarLinea", ReplyAction="*")]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse> ActivarDesactivarLineaAsync(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest request);
        
        // CODEGEN: Generating message contract since element name fechaCalculo from namespace http://wsproveedor1.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/CalcularCobroPostpago", ReplyAction="*")]
        MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse CalcularCobroPostpago(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsproveedor1.org/CalcularCobroPostpago", ReplyAction="*")]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse> CalcularCobroPostpagoAsync(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicio", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequestBody Body;
        
        public IngresarNuevoServicioRequest() {
        }
        
        public IngresarNuevoServicioRequest(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado;
        
        public IngresarNuevoServicioRequestBody() {
        }
        
        public IngresarNuevoServicioRequestBody(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            this.numeroTelefono = numeroTelefono;
            this.idTelefono = idTelefono;
            this.idTarjeta = idTarjeta;
            this.tipo = tipo;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarNuevoServicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarNuevoServicioResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponseBody Body;
        
        public IngresarNuevoServicioResponse() {
        }
        
        public IngresarNuevoServicioResponse(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class IngresarNuevoServicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MenuConsola.ServiceReferenceMenu.RespuestaIngresarServicio IngresarNuevoServicioResult;
        
        public IngresarNuevoServicioResponseBody() {
        }
        
        public IngresarNuevoServicioResponseBody(MenuConsola.ServiceReferenceMenu.RespuestaIngresarServicio IngresarNuevoServicioResult) {
            this.IngresarNuevoServicioResult = IngresarNuevoServicioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivarDesactivarLineaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivarDesactivarLinea", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequestBody Body;
        
        public ActivarDesactivarLineaRequest() {
        }
        
        public ActivarDesactivarLineaRequest(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class ActivarDesactivarLineaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idTarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string identificacionDuenio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string estado;
        
        public ActivarDesactivarLineaRequestBody() {
        }
        
        public ActivarDesactivarLineaRequestBody(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string identificacionDuenio, string estado) {
            this.numeroTelefono = numeroTelefono;
            this.idTelefono = idTelefono;
            this.idTarjeta = idTarjeta;
            this.tipo = tipo;
            this.identificacionDuenio = identificacionDuenio;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivarDesactivarLineaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivarDesactivarLineaResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponseBody Body;
        
        public ActivarDesactivarLineaResponse() {
        }
        
        public ActivarDesactivarLineaResponse(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class ActivarDesactivarLineaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MenuConsola.ServiceReferenceMenu.RespuestaActivarDesactivar ActivarDesactivarLineaResult;
        
        public ActivarDesactivarLineaResponseBody() {
        }
        
        public ActivarDesactivarLineaResponseBody(MenuConsola.ServiceReferenceMenu.RespuestaActivarDesactivar ActivarDesactivarLineaResult) {
            this.ActivarDesactivarLineaResult = ActivarDesactivarLineaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularCobroPostpagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularCobroPostpago", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequestBody Body;
        
        public CalcularCobroPostpagoRequest() {
        }
        
        public CalcularCobroPostpagoRequest(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class CalcularCobroPostpagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechaCalculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechaMaxPago;
        
        public CalcularCobroPostpagoRequestBody() {
        }
        
        public CalcularCobroPostpagoRequestBody(string fechaCalculo, string fechaMaxPago) {
            this.fechaCalculo = fechaCalculo;
            this.fechaMaxPago = fechaMaxPago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularCobroPostpagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularCobroPostpagoResponse", Namespace="http://wsproveedor1.org/", Order=0)]
        public MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponseBody Body;
        
        public CalcularCobroPostpagoResponse() {
        }
        
        public CalcularCobroPostpagoResponse(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsproveedor1.org/")]
    public partial class CalcularCobroPostpagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MenuConsola.ServiceReferenceMenu.RespuestaCalculoPostpago CalcularCobroPostpagoResult;
        
        public CalcularCobroPostpagoResponseBody() {
        }
        
        public CalcularCobroPostpagoResponseBody(MenuConsola.ServiceReferenceMenu.RespuestaCalculoPostpago CalcularCobroPostpagoResult) {
            this.CalcularCobroPostpagoResult = CalcularCobroPostpagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSProveedorSoapChannel : MenuConsola.ServiceReferenceMenu.WSProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSProveedorSoapClient : System.ServiceModel.ClientBase<MenuConsola.ServiceReferenceMenu.WSProveedorSoap>, MenuConsola.ServiceReferenceMenu.WSProveedorSoap {
        
        public WSProveedorSoapClient() {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse MenuConsola.ServiceReferenceMenu.WSProveedorSoap.IngresarNuevoServicio(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest request) {
            return base.Channel.IngresarNuevoServicio(request);
        }
        
        public MenuConsola.ServiceReferenceMenu.RespuestaIngresarServicio IngresarNuevoServicio(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest inValue = new MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.estado = estado;
            MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse retVal = ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).IngresarNuevoServicio(inValue);
            return retVal.Body.IngresarNuevoServicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse> MenuConsola.ServiceReferenceMenu.WSProveedorSoap.IngresarNuevoServicioAsync(MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest request) {
            return base.Channel.IngresarNuevoServicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioResponse> IngresarNuevoServicioAsync(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string estado) {
            MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest inValue = new MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.IngresarNuevoServicioRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.estado = estado;
            return ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).IngresarNuevoServicioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse MenuConsola.ServiceReferenceMenu.WSProveedorSoap.ActivarDesactivarLinea(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest request) {
            return base.Channel.ActivarDesactivarLinea(request);
        }
        
        public MenuConsola.ServiceReferenceMenu.RespuestaActivarDesactivar ActivarDesactivarLinea(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string identificacionDuenio, string estado) {
            MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest inValue = new MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.identificacionDuenio = identificacionDuenio;
            inValue.Body.estado = estado;
            MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse retVal = ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).ActivarDesactivarLinea(inValue);
            return retVal.Body.ActivarDesactivarLineaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse> MenuConsola.ServiceReferenceMenu.WSProveedorSoap.ActivarDesactivarLineaAsync(MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest request) {
            return base.Channel.ActivarDesactivarLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaResponse> ActivarDesactivarLineaAsync(string numeroTelefono, string idTelefono, string idTarjeta, string tipo, string identificacionDuenio, string estado) {
            MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest inValue = new MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.ActivarDesactivarLineaRequestBody();
            inValue.Body.numeroTelefono = numeroTelefono;
            inValue.Body.idTelefono = idTelefono;
            inValue.Body.idTarjeta = idTarjeta;
            inValue.Body.tipo = tipo;
            inValue.Body.identificacionDuenio = identificacionDuenio;
            inValue.Body.estado = estado;
            return ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).ActivarDesactivarLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse MenuConsola.ServiceReferenceMenu.WSProveedorSoap.CalcularCobroPostpago(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest request) {
            return base.Channel.CalcularCobroPostpago(request);
        }
        
        public MenuConsola.ServiceReferenceMenu.RespuestaCalculoPostpago CalcularCobroPostpago(string fechaCalculo, string fechaMaxPago) {
            MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest inValue = new MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequestBody();
            inValue.Body.fechaCalculo = fechaCalculo;
            inValue.Body.fechaMaxPago = fechaMaxPago;
            MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse retVal = ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).CalcularCobroPostpago(inValue);
            return retVal.Body.CalcularCobroPostpagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse> MenuConsola.ServiceReferenceMenu.WSProveedorSoap.CalcularCobroPostpagoAsync(MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest request) {
            return base.Channel.CalcularCobroPostpagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoResponse> CalcularCobroPostpagoAsync(string fechaCalculo, string fechaMaxPago) {
            MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest inValue = new MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequest();
            inValue.Body = new MenuConsola.ServiceReferenceMenu.CalcularCobroPostpagoRequestBody();
            inValue.Body.fechaCalculo = fechaCalculo;
            inValue.Body.fechaMaxPago = fechaMaxPago;
            return ((MenuConsola.ServiceReferenceMenu.WSProveedorSoap)(this)).CalcularCobroPostpagoAsync(inValue);
        }
    }
}
