//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONO
    {
        public int ID_BONO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<int> TELEFONO { get; set; }
    
        public virtual TELEFONO TELEFONO1 { get; set; }
    }
}
