//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COBRO()
        {
            this.DETALLE_COBROS = new HashSet<DETALLE_COBROS>();
        }
    
        public int ID_COBRO { get; set; }
        public System.DateTime FECHA_CALCULO { get; set; }
        public System.DateTime FECHA_M_PAGO { get; set; }
        public decimal COBRO_TOTAL { get; set; }
        public System.DateTime FECHA_COBRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COBROS> DETALLE_COBROS { get; set; }
    }
}
