//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COBROS()
        {
            this.DETALLE_COBROS = new HashSet<DETALLE_COBROS>();
        }
    
        public int ID_COBRO { get; set; }
        public System.DateTime FECHA_CALCULO { get; set; }
        public System.DateTime FECHA_M_PAGO { get; set; }
        public decimal COBRO_TOTAL { get; set; }
        public System.DateTime FECHA_COBRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COBROS> DETALLE_COBROS { get; set; }
    }
}
