//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COBROS
    {
        public int ID_DETALLE { get; set; }
        public int ID_COBRO { get; set; }
        public int ID_CLIENTE { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public string ESTADO_PAGO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual COBROS COBROS { get; set; }
    }
}
