//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COBROS
    {
        public int ID_DETALLE { get; set; }
        public int ID_COBRO { get; set; }
        public int ID_CLIENTE { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public string ESTADO_PAGO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COBRO COBRO { get; set; }
    }
}
