//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLAMADAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LLAMADAS()
        {
            this.TRANSACCIONES = new HashSet<TRANSACCIONES>();
        }
    
        public int ID_LLAMADA { get; set; }
        public string NUMTELEFONO_ORIGEN { get; set; }
        public string NUMTELEFONO_DESTINO { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public decimal COSTO { get; set; }
        public string DURACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
