//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMPANIA_TELEFONICAEntities : DbContext
    {
        public COMPANIA_TELEFONICAEntities()
            : base("name=COMPANIA_TELEFONICAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BONOS> BONOS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<COBROS> COBROS { get; set; }
        public virtual DbSet<CODIGO_PAIS> CODIGO_PAIS { get; set; }
        public virtual DbSet<ESTADOS_TELEFONOS> ESTADOS_TELEFONOS { get; set; }
        public virtual DbSet<LLAMADAS> LLAMADAS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TELEFONOS> TELEFONOS { get; set; }
        public virtual DbSet<TIPO_TELEFONO> TIPO_TELEFONO { get; set; }
        public virtual DbSet<TIPO_TRANSACCION> TIPO_TRANSACCION { get; set; }
        public virtual DbSet<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
