//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELEFONOS()
        {
            this.BONOS = new HashSet<BONOS>();
        }
    
        public int ID_TELEFONO { get; set; }
        public string NUM_TELEFONO { get; set; }
        public int ID_CODIGO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public int TIPO_TELEFONO { get; set; }
        public decimal SALDO { get; set; }
        public string IDENTIFICADOR_TARJETA { get; set; }
        public string IDENTIFICADOR_TELEFONO { get; set; }
        public int ID_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONOS> BONOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CODIGO_PAIS CODIGO_PAIS { get; set; }
        public virtual TIPO_TELEFONO TIPO_TELEFONO1 { get; set; }
    }
}
