//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELEFONO()
        {
            this.BONOS = new HashSet<BONO>();
        }
    
        public int ID_TELEFONO { get; set; }
        public string NUM_TELEFONO { get; set; }
        public int ID_CODIGO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public int TIPO_TELEFONO { get; set; }
        public decimal SALDO { get; set; }
        public string IDENTIFICADOR_TARJETA { get; set; }
        public string IDENTIFICADOR_TELEFONO { get; set; }
        public int ID_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONO> BONOS { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CODIGO_PAIS CODIGO_PAIS { get; set; }
        public virtual TIPO_TELEFONO TIPO_TELEFONO1 { get; set; }
    }
}
