//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES
    {
        public int ID_TRANSACCION { get; set; }
        public Nullable<int> ID_T_TRANS { get; set; }
        public Nullable<int> ID_LLAMADA { get; set; }
    
        public virtual LLAMADAS LLAMADAS { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
    }
}
