//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSProveedor1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONE
    {
        public int ID_TRANSACCION { get; set; }
        public Nullable<int> ID_T_TRANS { get; set; }
        public Nullable<int> ID_LLAMADA { get; set; }
    
        public virtual LLAMADA LLAMADA { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
    }
}
